name: SS6PlayerForCpp for macOS

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: release build
      run: ./scripts/release_macos.sh Release
